codes = {
    "3M": "745",
    "A-LIFT": "TA4",
    "ABB": "181",
    "ABEKO": "Q42",
    "ABM": "Z89",
    "ABSODAN": "FR0",
    "ABUS": "FB6",
    "AC-DELCO": "029",
    "ACLA": "905",
    "ADDA": "CW3",
    "ADIATEK": "PU9",
    "ADVANCED D.C.MOTORS": "K43",
    "AEG": "174",
    "AGRIA-AGRIMAC": "KT5",
    "AICHI": "AM4",
    "AIRAX": "D52",
    "AIRO": "kn3",
    "AIRPRESS": "T30",
    "AISAN": "889",
    "AISLE-MASTER": "JE1",
    "ALBATROS": "YZ1",
    "ALBRIGHT": "376",
    "ALESCO": "YQ3",
    "ALGAS": "010",
    "ALKE": "XB2",
    "ALL. IND.": "TR8",
    "ALLEN-BRADLEY": "G76",
    "ALLIBERT": "AF2",
    "ALLIS CHALMERS(KALMAR USA)": "006",
    "ALLISON": "571",
    "ALTO CLEANING": "IE3",
    "AMA": "W47",
    "AMEISE": "CI4",
    "AMELEC": "824",
    "AMER": "V83",
    "AMERICAN LINCOLN": "G30",
    "AMETEK": "I18",
    "AMLIFT": "JM5",
    "AMP": "642",
    "AMRE": "L44",
    "ANDERSON": "078",
    "ANSELL": "JD6",
    "ANTEO": "QT9",
    "APEM": "N60",
    "ARAL": "05I",
    "ARCOLECTRIC": "U83",
    "ARGO FILTER": "304",
    "ARMANNI": "P87",
    "ARMAX": "L30",
    "ARTISON": "CV4",
    "AS SCHWABE": "VZ5",
    "ASEA": "I06",
    "ASM": "AK0",
    "ATA": "X14",
    "ATE": "152",
    "ATEC": "TV3",
    "ATIB": "X54",
    "ATIB ELETTRONICA": "EV8",
    "ATLAS": "320",
    "ATLET": "506",
    "ATN": "GT9",
    "AUDUREAU": "F24",
    "AURAMO": "i09",
    "AUSA": "X89",
    "AUTRONIC": "DG9",
    "AVANT": "RZ5",
    "BACO": "L51",
    "BAHCO": "EM7",
    "BAKA": "Q09",
    "BAKER": "017",
    "BALBONI": "Q40",
    "BALDWIN": "072",
    "BALKANCAR": "647",
    "BANDAGEN": "221",
    "BAOLI": "T75",
    "BARDAHL": "DS5",
    "BARRETT (NISSAN)": "012",
    "BARTEC": "S09",
    "BATTERY SUPPLIES": "T65",
    "BATTIONI E PAGANI": "645",
    "BAUMANN": "a97",
    "BAUMER ELECTRIC": "AT4",
    "BAUSER": "605",
    "BCA": "110",
    "BD-LIFT": "XN6",
    "BEAM": "005",
    "BEARING": "d35",
    "BEHRENS EUROLIFT": "NX8",
    "BEI DUNCAN": "V80",
    "BEIJING FORKLIFT": "767",
    "BELET": "CH0",
    "BELOTTI": "M84",
    "BENDI": "DC0",
    "BENDIX": "064",
    "BENEDIKT & JAGER": "Y38",
    "BENEPARTS": "TQ8",
    "BERG": "844",
    "BERNSTEIN": "F73",
    "BERU": "513",
    "BESSEY": "R44",
    "BEST MOTOR": "V84",
    "BETA": "FE8",
    "BGS TECHNIC": "02Q",
    "BIG JOE": "T97",
    "BINDER": "J29",
    "BINDER CONNECTOR": "EM1",
    "BIRAL": "C54",
    "BISHAMON": "713",
    "BKS": "314",
    "BLUELIFT": "UQ3",
    "BOBCAT": "274",
    "BOLZONI": "386",
    "BOMA": "DX5",
    "BOMAQ": "SA8",
    "BONDERITE": "US4",
    "BONSER": "945",
    "BORG WARNER": "046",
    "BOSCH": "027",
    "BOSS": "B77",
    "BOSTIK": "G78",
    "BOURNS": "J24",
    "BOWER": "334",
    "BP OIL": "05J",
    "BRAD HARRISON": "558",
    "BRADY": "206",
    "BRAUCKE": "FD7",
    "BRAVI": "sp3",
    "BRETER": "Y28",
    "BREVETTI STENDALTO": "U76",
    "BRIGADE": "M77",
    "BROMMA": "Q36",
    "BROWN BOVERY": "575",
    "BRUNILIFT": "316",
    "BT": "268",
    "BULLI/FRANZ KAHL": "317",
    "BULMOR": "RG3",
    "BURGESS": "168",
    "BURNDY": "934",
    "BUSSMANN": "511",
    "BV- VESTERGAARD": "685",
    "B\u00c4R": "DR4",
    "CABLEFORM": "169",
    "CAM": "D03",
    "CANGARU": "DR9",
    "CAPACITY": "MR6",
    "CARER": "Y61",
    "CARGO TRACK": "GE3",
    "CARIX": "CJ0",
    "CARLINGSWITCH": "N54",
    "CARLO GAVAZZI": "U24",
    "CARRARO": "948",
    "CARREFFE": "Y12",
    "CASCADE": "050",
    "CASE": "636",
    "CASTROL": "AU9",
    "CATERPILLAR": "009",
    "CAV": "053",
    "CENTURY GAS": "774",
    "CESAB": "A45",
    "CFR": "X34",
    "CHAR-LYNN": "059",
    "CHARLATTE": "I70",
    "CHICAGO RAWHIDE": "084",
    "CHINFA": "QX6",
    "CHLORIDE": "751",
    "CIAM": "V17",
    "CIMEX": "DW6",
    "CLARK": "007",
    "CLARKE CLEANING MACHINERY": "I28",
    "CLAROSTAT": "R79",
    "CLEANFIX": "DW5",
    "CLIMAX": "DW9",
    "CLIMAX (KALMAR-UK)": "184",
    "CLUBCAR": "FW1",
    "COBO-MT": "C36",
    "COLE HERSEE": "307",
    "COLTRADING": "ER0",
    "COLUMBUS": "DW4",
    "COMAC": "DW3",
    "COMBILIFT": "AY7",
    "COMEPI": "QH8",
    "COMESYS": "DA2",
    "COMMANDER": "GX3",
    "COMMERCIAL HYDRAULICS": "242",
    "COMUS": "QN2",
    "CONTELEC": "092",
    "CONTINENTAL": "023",
    "CONVEYANCE": "c77",
    "CPI": "C19",
    "CRAIG AND DERRI": "705",
    "CRC": "L63",
    "CREDE": "646",
    "CROSLAND": "077",
    "CROUZET": "629",
    "CROWN": "002",
    "CROWN BATTERY": "QF5",
    "CTC": "N20",
    "CTI": "cy7",
    "CUMMINS": "183",
    "CURTIS": "910",
    "CUSHMAN": "281",
    "CUSTOMIZED REFERENCE": "cus",
    "CUTLER-HAMMER": "CR8",
    "CVS FERRARI": "P14",
    "CYNEL": "ZE5",
    "DAEWOO": "954",
    "DAIMLER-BENZ": "163",
    "DALIAN": "EJ2",
    "DAMBACH": "W19",
    "DAMOLIN": "FS1",
    "DANA": "522",
    "DANAHER-MOTION": "DF6",
    "DANFOSS": "550",
    "DANTRUCK": "p10",
    "DATASENSOR": "DO4",
    "DATCON": "F58",
    "DAUTEL": "DR5",
    "DAV": "592",
    "DAVIS ACCESS": "gr9",
    "DAYCO": "104",
    "DEB STOKO": "YS3",
    "DEC": "qv2",
    "DECA": "F66",
    "DELCO-REMY": "093",
    "DELPHI": "S53",
    "DELTA DESIGN": "H31",
    "DELTA-Q": "FN8",
    "DELTAIR": "GS4",
    "DELTROL CONTROLS": "P46",
    "DEMKE ELECTRONIC": "Y15",
    "DERAY": "Q65",
    "DESTA": "744",
    "DEUTSCH": "Q53",
    "DEUTZ": "380",
    "DEWALT": "DL3",
    "DHOLLANDIA": "DR3",
    "DIECI": "Z71",
    "DIGGER PARTS": "YM3",
    "DIGISOUND": "T66",
    "DIMOS": "XB8",
    "DINGLI": "RX7",
    "DINO LIFT": "BJ9",
    "DIXSON-AMETEK": "BS4",
    "DL CHEMICALS": "S60",
    "DONALDSON": "073",
    "DONKEY": "RQ3",
    "DORMAN SMITH": "T24",
    "DOUGLAS": "901",
    "DOWTY": "956",
    "DREUMEX": "UP3",
    "DUCATI": "282",
    "DUCELIER": "459",
    "DULEVO": "Q87",
    "DUPLEX": "DW2",
    "DURWEN": "Y58",
    "DUTTON-LAINSON": "EQ7",
    "DYNO": "Z41",
    "E-WAY": "JG1",
    "EBAC": "ZK9",
    "EBM": "K19",
    "ECCO": "H48",
    "ECOLIFT": "AL0",
    "ECONOMY": "BN9",
    "ECONOMY FUSE": "512",
    "EFECTOR": "I91",
    "EFEL": "X84",
    "EFEN": "607",
    "EHPO": "QQ3",
    "EKDGELENKROHR": "N66",
    "ELAN": "B59",
    "ELEC SPARE PART": "348",
    "ELECAR": "559",
    "ELECTROLUX": "DW1",
    "ELEKTRON": "A47",
    "ELEKTROSISTEM": "M06",
    "ELF": "AU7",
    "ELFIN": "BH6",
    "ELME": "923",
    "ELOBAU": "BE9",
    "ELORA": "SS4",
    "ELS": "ZF3",
    "EM": "798",
    "EM BRNO": "CI9",
    "EMILY": "0K9",
    "EMM": "Z39",
    "EMPTEEZY": "W27",
    "ENERGECO": "F89",
    "ENERGIC PLUS": "US7",
    "ENGINE TEAM": "0G8",
    "EP": "BB8",
    "EP FORKLIFT": "JC3",
    "ERGOBJORN": "CV6",
    "ERHEL HYDRIS": "DC6",
    "ERSCE": "T23",
    "ESAB": "Q84",
    "ESKA": "C92",
    "ESSELINGEN": "624",
    "ESSEX": "I55",
    "ESSO": "AV0",
    "ETA": "I77",
    "ETRI": "P71",
    "EUREKA": "ex0",
    "EUROL LUBRICANTS": "W96",
    "EUROLIFTER": "237",
    "EUROPART": "BL6",
    "EUROYEN": "DI7",
    "EVERUN": "ZF7",
    "EW HOF": "U26",
    "EXIDE": "K06",
    "EXPRESSO": "AY1",
    "EXTREME": "AV6",
    "EZ-GO": "GE1",
    "FABA": "F09",
    "FAC": "156",
    "FACOM": "N70",
    "FACTORY CAT": "ID8",
    "FAG": "038",
    "FALCONLIFT": "PC2",
    "FANTUZZI": "B71",
    "FARESIN TELEHANDLERS": "KX7",
    "FAST": "XN4",
    "FAURECIA": "AW8",
    "FEDERAL SIGNAL": "CR1",
    "FEELER": "JF4",
    "FEME": "P24",
    "FENDT": "321",
    "FENWICK": "256",
    "FERRAZ": "655",
    "FERRODO": "709",
    "FERVE": "L14",
    "FIAT": "260",
    "FIAT HITACHI": "M18",
    "FIMAP": "DW0",
    "FIMSA": "EN7",
    "FINA": "AU6",
    "FIORA": "CR2",
    "FIORENTINI": "188",
    "FLEETGUARD": "076",
    "FLOJET": "t81",
    "FLOOR": "DV9",
    "FLOORPUL": "ES8",
    "FLOYD BELL": "FD3",
    "FLUKE": "R70",
    "FMC": "335",
    "FOCOLIFT": "XW1",
    "FORCE": "GC2",
    "FORD": "090",
    "FORTE": "DP7",
    "FRAM": "069",
    "FRANCE HAYON SERVICE": "Z56",
    "FREI": "B61",
    "FRITZ KUBLER": "AD2",
    "FTMH": "SF6",
    "FUCHS": "U04",
    "FUJI": "H61",
    "G.POWER": "EI9",
    "GABELN (428) CAM": "428",
    "GABELN (628) OEM": "628",
    "GANSOW": "DV8",
    "GARMIN": "BF8",
    "GARPHYTTAN": "F08",
    "GATES": "086",
    "GEDORE": "R20",
    "GEHL": "DR7",
    "GENERAL ELECTRIC": "080",
    "GENGE & THOMA": "DL4",
    "GENIE": "T21",
    "GENKINGER": "c50",
    "GESSMANN": "G19",
    "GHIBLI": "NZ9",
    "GHIELMETTI": "R16",
    "GIANT": "WP9",
    "GM MOTORS": "556",
    "GM-IMPCO": "BQ0",
    "GMATICDRGANSOW": "NS7",
    "GODREJ": "N97",
    "GOJO": "DX8",
    "GOLDHOFER": "GF3",
    "GOODSENSE": "PS8",
    "GOTTWALD": "KZ8",
    "GOULD": "239",
    "GOUPIL": "DS4",
    "GRADALL": "KJ1",
    "GRAMMER": "230",
    "GREGOIRE-BARILLEAU": "XE6",
    "GROTE & HARTMANN": "BH1",
    "GROVE": "B43",
    "GYS": "RA8",
    "HACO": "DG8",
    "HAFA": "DS9",
    "HAKO": "829",
    "HALLA": "L25",
    "HALLINS": "BD4",
    "HAMECH": "N65",
    "HAMLIN": "DR2",
    "HANGCHA  (HC)": "DG5",
    "HANSELIFTER": "IF8",
    "HARDELLET": "I57",
    "HARLAN": "830",
    "HARTING": "H78",
    "HARTMANN": "618",
    "HASCO": "M05",
    "HATZ": "M81",
    "HAULOTTE": "CI2",
    "HAWKER-OLDHAM": "AO9",
    "HAYAKAWA ELECTRIC": "DO6",
    "HAZET": "EU3",
    "HB SWITCH": "A04",
    "HCA": "YX6",
    "HEDEN": "B04",
    "HEFTER CLEANTECH": "0L4",
    "HELI": "U88",
    "HELLA": "526",
    "HENDLEY": "kp2",
    "HENKEL": "S93",
    "HENLEY": "346",
    "HERBST": "KZ4",
    "HERMACON": "PB5",
    "HERRMANN": "F40",
    "HERTH & BUSS": "a05",
    "HINOWA": "HB7",
    "HIRSCHMANN": "850",
    "HITACHI AERIAL PLATFORM": "GE6",
    "HITACHI ELECTRIC": "480",
    "HOBBS": "119",
    "HOIST": "CB0",
    "HOLLAND LIFT": "CV2",
    "HOLTS": "DI9",
    "HONDA": "G04",
    "HONEYWELL": "288",
    "HOPPECKE": "Y71",
    "HOSIDEN BESSON": "CA7",
    "HPI": "654",
    "HU-LIFT": "224",
    "HUBTEX": "N29",
    "HURTH": "284",
    "HUVEMA": "TQ1",
    "HY-BRID LIFTS": "RM7",
    "HYDAC": "H46",
    "HYDRAFORCE": "i83",
    "HYDRECO": "048",
    "HYDROMEK": "PA6",
    "HYDROPARTS": "DE7",
    "HYLOMAR": "S45",
    "HYSTER": "001",
    "HYTSU": "DY0",
    "HYUNDAI": "Q72",
    "IBS": "TX6",
    "ICEM": "A28",
    "IFONIX": "BY1",
    "IGUS": "J72",
    "IHI": "V50",
    "IMPCO": "014",
    "INA": "111",
    "INCAB": "bk6",
    "INDAK": "CH2",
    "INDOS": "M17",
    "INDUSTRIESERVICEJUNG": "ISJ",
    "INSTANT": "TT9",
    "INTERFLON": "BD0",
    "INTERLIFT": "EI2",
    "INTRUPA": "079",
    "IPC": "EY7",
    "IPS": "CT0",
    "IR": "129",
    "IRION": "273",
    "IRWIN": "SQ4",
    "ISAL": "DV7",
    "ISKRA": "A12",
    "ISUZU": "134",
    "ITALMACCHINE": "FB5",
    "ITECO": "CV3",
    "ITT/CANNON": "P99",
    "ITW": "337",
    "IXYS": "L77",
    "JAC": "IM5",
    "JBT": "MR3",
    "JCB": "861",
    "JCHI": "RK8",
    "JELAU": "859",
    "JHECO": "PM6",
    "JIDECO": "A92",
    "JLG": "N92",
    "JODIMA": "DR1",
    "JOHN DEERE": "A23",
    "JONES (CLAAS)": "D88",
    "JR MERRITT": "IH9",
    "JULI": "Z48",
    "JUMBO": "P43",
    "JUNGHEINRICH (AMEISE)": "269",
    "KABELSCHLEPP": "F57",
    "KALMAR LMV (SWEDEN)": "546",
    "KAUP": "328",
    "KAYABA": "247",
    "KAYER": "BG2",
    "KCL": "ZT1",
    "KEB": "173",
    "KELVIN FORKTRUCKS": "CB2",
    "KEMTEX": "JS4",
    "KENDALL": "AV1",
    "KENDRION": "BX3",
    "KENTRUCK-ROBUR": "620",
    "KESSLER": "M52",
    "KETTENBOLZEN": "G86",
    "KETTENSCHLOSS": "927",
    "KETTENTYP 1 TOTALSOURCE": "q29",
    "KETTENTYP 2": "147",
    "KIEPE": "D18",
    "KINGLIFTER TERBERG": "DO9",
    "KINGSTATE": "DE1",
    "KISSLING": "F17",
    "KLINGSPOR": "fm7",
    "KLOCNER+MOELLER": "G58",
    "KLUBER LUBRICATION": "YE8",
    "KLUTHE": "DH0",
    "KNECHT": "345",
    "KNIPEX": "R51",
    "KNORR": "N44",
    "KNOTT": "G73",
    "KO-KEN": "BG9",
    "KOBELCO": "U33",
    "KOMATSU": "107",
    "KONECRANES": "F11",
    "KOOIAAP": "L01",
    "KORRESIONSFESTE KETTE": "s88",
    "KOSTAL": "573",
    "KOYO": "235",
    "KPC": "0E9",
    "KRAMER": "F60",
    "KRANZLE": "CZ9",
    "KRAUS & NAIMER": "H26",
    "KROON OIL": "PA8",
    "KUBLER": "873",
    "KUBOTA": "857",
    "KUKKO": "R80",
    "KYB": "AF6",
    "KYORITSU KEIKI": "U02",
    "K\u00c4RCHER": "Y32",
    "LAFIS": "860",
    "LAGER": "J71",
    "LAMB AMETEK": "U53",
    "LANCER": "KA5",
    "LANCER BOSS": "270",
    "LANSING BAGNALL": "271",
    "LASTEK": "925",
    "LATEC": "DH6",
    "LAVOR": "RQ7",
    "LBW": "TQ9",
    "LEATHERMAN": "SD4",
    "LEB": "101",
    "LEESON": "G28",
    "LEGRAND": "a09",
    "LEMMERZ": "164",
    "LENZE": "F34",
    "LEROY SOMMER": "517",
    "LESTER ELECTRICAL": "FK7",
    "LGM": "DJ9",
    "LGMG": "XQ8",
    "LIEBHERR": "EF3",
    "LIFTER": "CU1",
    "LIFTLUX": "cu4",
    "LIFTRITE": "Q68",
    "LINAK": "712",
    "LINDE": "400",
    "LINEMASTER": "U11",
    "LIQUI MOLY": "UX3",
    "LITTELFUSE": "A44",
    "LITTLE GIANT": "246",
    "LITTLE MULE": "Y17",
    "LMV": "689",
    "LOADMAC": "TV9",
    "LOC": "753",
    "LOCKSEAL": "S02",
    "LOCTITE": "734",
    "LOGITRANS": "d37",
    "LONKING FORKLIFT": "PF8",
    "LONTEX": "TR3",
    "LOPEZ": "TR6",
    "LOVATO-SCHAKELAAR": "N23",
    "LOXEAL": "07V",
    "LUBERFINER": "a50",
    "LUCAS": "026",
    "LUFTREIFEN": "640",
    "LUGLI": "C80",
    "LULL": "U05",
    "LUNA": "BW9",
    "MAFELEC": "ES9",
    "MAFI": "S04",
    "MAGAZINER": "DY2",
    "MAGKADDY": "WD9",
    "MAGLINER": "Y27",
    "MAGLITE": "X51",
    "MAGNETI MARELLI": "600",
    "MAGNI": "RK6",
    "MALLORY": "R68",
    "MANDIGERS": "371",
    "MANDO": "M88",
    "MANILEC": "CJ3",
    "MANITOU": "261",
    "MANN FILTER": "241",
    "MANTALL": "SG3",
    "MARADYNE": "V11",
    "MARIBA": "RF3",
    "MARIOTTI": "CL4",
    "MARKAL": "378",
    "MARKLIFT": "BU2",
    "MARQUARDT": "D12",
    "MARTOR": "ES6",
    "MASCOT": "P06",
    "MASETTI": "0KV",
    "MAST": "FK0",
    "MASTERMOVER": "HS2",
    "MATBRO": "B97",
    "MATO": "S32",
    "MATRIX": "Y21",
    "MATSUSHITA": "C96",
    "MAVOM": "JF5",
    "MAXIMAL": "FC8",
    "MAZDA": "395",
    "MBB": "DH3",
    "MCB-ELEKTRISCH": "H24",
    "MEANWELL": "DI6",
    "MEC": "CK0",
    "MECLUBE": "DN2",
    "MEIDEN": "664",
    "MENNEKES": "CV9",
    "MERCEDES (ENGINE)": "676",
    "MERIT": "342",
    "MERLINGERLIN": "285",
    "MERLO": "a24",
    "METEORLITE": "A31",
    "MEYER": "737",
    "MIAG": "a56",
    "MIB": "XF9",
    "MIC": "258",
    "MICO": "041",
    "MICRO SWITCH": "099",
    "MIDAC": "FU9",
    "MIDORI": "Y75",
    "MILLER": "JB1",
    "MILTAC": "750",
    "MINUTEMAN": "DM6",
    "MIRAGE": "DV6",
    "MISCO LOUDSPEAKER": "QP8",
    "MITSUBISHI": "272",
    "MITUTOYO": "225",
    "MITYVAC": "MB7",
    "MOBIL": "ZR1",
    "MOBILE SHUTTER DOORS": "XF4",
    "MOFFETT": "P48",
    "MOFLASH": "QP7",
    "MOL": "532",
    "MOLEX": "J64",
    "MOLYKOTE": "S56",
    "MONTINI": "G51",
    "MORA": "283",
    "MOTEC": "BG7",
    "MOTIP": "J03",
    "MOTORERSATZTEILE (H50)": "H50",
    "MOTOROLA": "H28",
    "MOTTEZ": "Z68",
    "MOVEXX": "IT2",
    "MOVIMOTOR": "UV6",
    "MTA": "K16",
    "MUJ": "V53",
    "MULAG": "DN4",
    "MULI": "808",
    "MULTI-CONTACT": "SU5",
    "MULTIONE": "XD4",
    "MULTITEL": "FQ0",
    "MURPHY": "CG5",
    "MUSTANG": "N91",
    "NAGARES": "N57",
    "NARROW AISLE": "EX1",
    "NARVA": "U56",
    "NAVISTAR": "ZR2",
    "NELCO": "G45",
    "NELCON": "MF9",
    "NETTUNO": "PZ7",
    "NEUSON": "HG1",
    "NEW HOLLAND": "N89",
    "NEXEN": "BC9",
    "NGK": "359",
    "NICHICON": "AC6",
    "NICHIYU-NYK": "469",
    "NIDEC": "JY1",
    "NIELSEN HOLST": "I40",
    "NIFTYLIFT": "AZ6",
    "NIKKI": "470",
    "NIKKO": "394",
    "NILCO": "DV5",
    "NILES": "564",
    "NILFISK - ADVANCE": "H45",
    "NILFISK ADVANCE": "AX9",
    "NIPPON PARTS": "B23",
    "NIPPON-DENSO": "028",
    "NISSAN-DATSUN": "057",
    "NMC-WOLLARD": "MT9",
    "NOBLELIFT": "IC8",
    "NOK": "485",
    "NORD DRIVESYSTEM": "JC2",
    "NOVATECH": "AY9",
    "NOVATIO": "AD1",
    "NO\u00cbLL": "MF8",
    "NSK-HOOVER": "042",
    "NTN": "398",
    "NUMATIC": "U97",
    "NUOVA DETAS": "L06",
    "NUOVA ELLETRA": "L65",
    "NYSTROM": "I36",
    "O & K": "639",
    "ODLS": "SN5",
    "OEHLER": "WQ2",
    "OEM CONTROLS": "Z70",
    "OGNIBENE ELETTROMECCANICA": "FF8",
    "OHBC": "WX6",
    "OHIO": "M72",
    "OIL & STEEL": "FL8",
    "OIL SISTEM": "DO0",
    "OLDHAM": "C74",
    "OM-PIMESPO-FIAT": "B41",
    "OMFORT": "275",
    "OMG": "I20",
    "OMRON": "476",
    "ONDERHOUD": "Q25",
    "OPTION TAPE": "WX9",
    "OSRAM": "567",
    "OTEHALL": "G07",
    "OTO": "TS3",
    "OTTAWA": "a33",
    "OUTRIGGER PADS": "0IQ",
    "OZAT": "YU3",
    "PACECO": "NA9",
    "PACIFIC SCIENTI": "916",
    "PALFINGER": "DR8",
    "PANDUIT": "Q61",
    "PAPST": "583",
    "PARIS-RHONE": "648",
    "PARIZZI": "Y78",
    "PARKER": "047",
    "PARKER HYDRAULICS": "FJ2",
    "PATRIA": "Q55",
    "PEC": "Z79",
    "PEFRA": "FT5",
    "PEG": "262",
    "PELJOB": "hh1",
    "PENNY & GILES": "P60",
    "PENRAY": "U25",
    "PEPPERL+FUCHS": "I54",
    "PERFILTER": "A87",
    "PERKINS": "054",
    "PERMATEX": "489",
    "PETEC": "0H3",
    "PETERCEM": "P89",
    "PETRY": "SV5",
    "PEUGEOT": "678",
    "PHILIPS": "478",
    "PHOENIX CONTACT": "Q28",
    "PIERALISI": "P05",
    "PILZ": "Z99",
    "PINTSCH-BUBENZER": "MS3",
    "PITTMAN": "088",
    "PIZZATO": "K39",
    "PLATINUM": "sr7",
    "POLLAK": "139",
    "PORTHOS": "264",
    "POTTER": "WB9",
    "POTTER & BRUMFIELD": "Q32",
    "POWER BOSS": "H66",
    "POWER FLITE": "DV3",
    "POWEREX": "N98",
    "POWERLIFTER": "PN3",
    "PPM": "H29",
    "PQ": "R78",
    "PRAMAC": "C43",
    "PRAT": "276",
    "PRECO": "D85",
    "PRESSOL": "R67",
    "PRESTOLITE": "051",
    "PRIME MOVER": "066",
    "PRINS": "H27",
    "PRO-TECH ANTI SLIP": "YX9",
    "PROCONECT": "686",
    "PROTO": "DB0",
    "PUDENZ": "C13",
    "PULIMAT": "N10",
    "PUROLATOR": "094",
    "Q8": "av2",
    "QFS": "BA1",
    "RAFI": "F44",
    "RAM": "MB9",
    "RANGER": "CG9",
    "RANSOMES": "259",
    "RAPID LIFT": "F88",
    "RAPID PARTS ADAPTALI": "WV5",
    "RATCLIFF": "EY6",
    "RAVAS": "D65",
    "RAVIOLI": "I45",
    "RAYMOND": "015",
    "RCM": "Q33",
    "REALS": "909",
    "REFERENCE": "K72",
    "REINZ": "213",
    "REITER": "N51",
    "REKOFA": "F38",
    "REMA": "723",
    "REMA TIP TOP": "0E0",
    "RENAULT": "746",
    "RENNSTEIG": "YY4",
    "REXNORD": "A26",
    "REXROTH": "581",
    "RIDGID": "S57",
    "RMF": "V89",
    "RMH": "D34",
    "ROBUSTUS": "CF7",
    "ROCKWELL": "233",
    "ROCLA": "806",
    "ROCOL": "CG6",
    "RODCRAFT": "226",
    "ROFAN": "IS1",
    "RONCARI": "N24",
    "ROQUET": "X77",
    "ROSLER": "GL2",
    "ROTOWASH": "DV0",
    "ROYAL": "CO5",
    "RS COMPONENTS": "CO2",
    "RUBENPOWER": "NU8",
    "RUKO GMBH PRECISION": "WQ6",
    "RUNSHARE": "TJ9",
    "RUTHMANN": "SD3",
    "RYCO": "AU0",
    "R\u00c4DER VOGEL": "B38",
    "SAFE-T-ALERT": "NJ1",
    "SAFETY JOGGER": "RA9",
    "SAFHOLLAND": "MS7",
    "SAIA": "848",
    "SAKAE": "K87",
    "SALEV": "265",
    "SAMAG - TRANSPALLET": "F20",
    "SAMBRON": "763",
    "SAMSUNG": "L67",
    "SAMUK": "ET4",
    "SANDERSON": "904",
    "SANY": "KM3",
    "SAUER-SUNSTRAND": "151",
    "SAUNDERS ELECTRONICS": "DM0",
    "SAVECO": "279",
    "SAXBY": "277",
    "SCANIA (ENGINE)": "K97",
    "SCHABMULLER": "491",
    "SCHALTBAU": "613",
    "SCHLAUCH": "941",
    "SCHLEGEL": "R29",
    "SCHLEMMER": "GD4",
    "SCHLUESSELNUMMER": "i37",
    "SCHMERSAL": "C31",
    "SCHNEEKETTEN": "J59",
    "SCHNEIDER": "B42",
    "SCHONBUCH": "S43",
    "SCHRACK": "G99",
    "SCHWEITZER": "Y29",
    "SCHYLLER": "AK1",
    "SCH\u00c4FFER": "PV4",
    "SDS-RELAIS": "U94",
    "SELCO": "DU9",
    "SEMAX": "EU1",
    "SEMIKRON": "822",
    "SERVOTEK": "AA3",
    "SESALY": "QX4",
    "SETON": "N50",
    "SEV-MARCHAL": "700",
    "SEV-MOTOROLA": "P19",
    "SEVCON": "150",
    "SHANGLI": "EJ1",
    "SHELL": "AU8",
    "SHINKO": "834",
    "SIBA": "A95",
    "SIBICAR": "EX7",
    "SICHELSCHMIDT": "683",
    "SICK": "Y20",
    "SICOMET": "U68",
    "SIDETRACKER": "WY9",
    "SIEMENS": "574",
    "SIEVERT": "EV6",
    "SIGNET SYSTEMS": "EU0",
    "SIKAFLEX": "Y07",
    "SIMAI": "AJ9",
    "SIMALUBE": "03E",
    "SIMON": "BV0",
    "SINOBOOM": "sy8",
    "SIRENA": "D80",
    "SIROCCO": "J49",
    "SIROCO": "JY5",
    "SISU": "F51",
    "SKF": "044",
    "SKYJACK": "AK4",
    "SME ELETTRONICA": "EV7",
    "SMH": "123",
    "SNAPON": "S37",
    "SNORKEL": "Q23",
    "SNR": "324",
    "SOCAGE": "WE2",
    "SOERENSEN": "JG2",
    "SORMA": "DU8",
    "SOUDAL": "Q46",
    "SOVAM": "RP3",
    "SPAL": "L90",
    "SPE": "N63",
    "SPEAKER": "K99",
    "SPECTROL": "G64",
    "SPICER": "372",
    "SPIJKSTAAL": "H77",
    "SPOHN+BURKHARDT": "B30",
    "SPRAYMART": "ZB2",
    "SPUITBUSSEN": "J40",
    "SQUARE D": "306",
    "STABILUS": "562",
    "STAHL-EX": "S33",
    "STAHLWILLE": "Q86",
    "STANLEY": "B65",
    "STARK": "322",
    "STEINBOCK": "267",
    "STELLANA": "K09",
    "STEUTE": "F79",
    "STIEBEL ELTRON": "CD1",
    "STILL": "255",
    "STINIS": "FW8",
    "STOCKA": "h40",
    "STOECKLIN": "h38",
    "STOKO": "JP6",
    "STROMAG": "V81",
    "SULO": "CF4",
    "SUMITOMO": "483",
    "SUNON": "DS0",
    "SUNWARD": "JM9",
    "SUPERHELP": "KY2",
    "SUSPA": "693",
    "SVETRUCK": "993",
    "SWARFEGA": "04K",
    "SWF": "543",
    "SWINGLIFT": "X27",
    "SYNCHRO-START": "N09",
    "TAILIFT": "B11",
    "TAKEUCHI": "BV4",
    "TARGET TECH": "DN1",
    "TARSO": "TR9",
    "TASKI": "T61",
    "TAYLOR": "W98",
    "TAYLOR-DUNN": "J54",
    "TCM": "140",
    "TECNOCAR": "266",
    "TEHA": "TQ6",
    "TEKNOVA": "S27",
    "TELECO": "M09",
    "TELEMECANIQUE": "312",
    "TELWIN": "TW7",
    "TEMPORITI": "G29",
    "TEND": "AC7",
    "TENGTOOLS": "RH6",
    "TENNANT": "347",
    "TERBERG": "d21",
    "TEREX": "F74",
    "TEREX AERIALS": "FL4",
    "TEROSON": "FP9",
    "TEUPEN": "hm2",
    "TEXACO": "AV3",
    "TEXELCO": "wa7",
    "TH-CONTACT": "CO9",
    "THALER": "RM3",
    "THOMAS": "F33",
    "THOROUGHBRED": "PV8",
    "THREEBOND": "S55",
    "THRIGE-TITAN": "K36",
    "THWAITES": "TK1",
    "TICO": "MG8",
    "TIGER GRIP": "YZ7",
    "TIGER TRACTOR": "JY3",
    "TIMKEN": "036",
    "TIMSAN": "XX9",
    "TISEL": "XK2",
    "TLD": "QC6",
    "TLPE": "RS7",
    "TOLLO LINEAR": "CC1",
    "TOLSA": "YW3",
    "TORK": "WR2",
    "TORRINGTON": "211",
    "TOSHIBA": "D72",
    "TOTAL": "AU5",
    "TOTALLIFTER": "DX2",
    "TOTALSOURCE": "CC2",
    "TOYODA AUTOMATIC LOOM": "K14",
    "TOYOTA": "058",
    "TRACMA": "N71",
    "TRANSMANUT": "QV9",
    "TREK CLEANING MACHINES": "JN3",
    "TREX PARTS": "TRX",
    "TRIDON": "301",
    "TRISTAR": "KU1",
    "TROJAN": "W04",
    "TROMBETTA": "AU1",
    "TUDOR": "165",
    "TUG": "FE1",
    "TURCK": "DT7",
    "TVH": "TVH",
    "ULTRA -HYDRAUILCS": "525",
    "UMETA": "S36",
    "UMS": "JD3",
    "UN FORKLIFT": "MY7",
    "UNBEKANNT": "999",
    "UNELEC": "582",
    "UNICARRIER": "RN5",
    "UNIL": "AV4",
    "UNITRAC": "602",
    "UNIVERSAL MACHINE SO": "TX7",
    "UNKNOWN": "GDI",
    "UPRIGHT": "BH2",
    "UTILEV": "QK3",
    "UVEX": "R81",
    "VALEO": "F19",
    "VALMET": "680",
    "VALVOLINE": "CS2",
    "VARTA": "772",
    "VDO": "149",
    "VECOM": "B45",
    "VEILIGHEID": "Q26",
    "VEM MOTORS": "BL0",
    "VERF": "930",
    "VERSALIFT": "WE3",
    "VERTIMAC": "TB8",
    "VESTERGAARD": "AG7",
    "VIALUX": "UZ5",
    "VIBA": "FA6",
    "VICKERS": "049",
    "VICTRON": "S06",
    "VILECTRA": "q60",
    "VISATON": "EJ9",
    "VISOLUX": "114",
    "VKP": "CP0",
    "VM MOTORI (ENGINE)": "L19",
    "VOITH": "560",
    "VOLK": "FT4",
    "VOLKSWAGEN": "504",
    "VOLLGUMMIREIFEN": "650",
    "VOLTAS": "N58",
    "VOLVO": "812",
    "VOSS HELME": "SX7",
    "VOTEX-BISON": "IM2",
    "WABCO": "928",
    "WACKER NEUSON": "G75",
    "WAGNER": "677",
    "WAGNER-LOCKHEAD": "067",
    "WAGO": "CO8",
    "WALSTED": "q18",
    "WARNERELECTRIC": "P12",
    "WAUKESHA": "122",
    "WAYNE": "777",
    "WD40": "ty1",
    "WEBASTO": "727",
    "WEHRLE": "309",
    "WEIDEMANN": "PD3",
    "WEIDMULLER": "S97",
    "WELDA": "YW2",
    "WERA": "DA5",
    "WERMA": "T11",
    "WESTINGHOUSE": "062",
    "WETROK": "DU7",
    "WHIPTRUCK": "DI0",
    "WICKE": "b69",
    "WIENOLD LIFTE": "0I6",
    "WIGREX": "XN5",
    "WIJLHUIZEN": "NV1",
    "WILLIAMS CONTROLS": "CC6",
    "WINDSOR": "DU6",
    "WINKLER": "RN6",
    "WIRBEL": "du5",
    "WITTE": "UV2",
    "WIX": "075",
    "WM": "TR7",
    "WOODWARD": "DF8",
    "WURTH": "588",
    "XILIN": "Y25",
    "XINCHAI": "JI2",
    "YALE": "003",
    "YAM/YANG": "B09",
    "YAMAHA": "G03",
    "YAMAHA GOLF CAR": "989",
    "YANMAR": "805",
    "YAZAKI": "A35",
    "YEC": "544",
    "YOKOTA": "XG4",
    "YOUNGMAN": "SS6",
    "ZANDER": "638",
    "ZAPI": "I12",
    "ZECA": "b12",
    "ZEPRO": "EN8",
    "ZETTLER": "T91",
    "ZF": "115",
    "ZIVAN": "W05",
    "ZPMC": "MC2",
    "ZUS\u00c4TZLICHE KOSTEN": "m99",
    "ohne Marke": "999"
}